---
title: "Data-581 Lab 4"
author: "Dhun Sheth"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(HMM)
library(LearnBayes)
```

## Question 2
```{r question_2}

pi.fun <- function(i) {
  out <- 0
  if (i > 0) out <- 1/(i+1)^3
  out
}

N <- 20000
X <- numeric(N)
current.state <- 50 # initialize the Markov chain
for (n in 1:N) {
  i <- current.state
  P <- c(min(pi.fun(i-2)/pi.fun(i), 1), 
         min(pi.fun(i-1)/pi.fun(i), 1),
         min(pi.fun(i+1)/pi.fun(i), 1),
         min(pi.fun(i+2)/pi.fun(i), 1))/6
  P0 <- 1 - sum(P)
  P <- c(P[1:2], P0, P[3:4])
  transition <- sample(seq(-2,2,1), size = 1, prob = P)
  current.state <- current.state + transition
  X[n] <- current.state
}
n <-1000
observedDist <- table(X[-c(1:n)]) # removing first 1000 observations "burn-in period"
pi <- observedDist/(N-n)

k_est = pi[2]*(3^3)
print(k_est)

```

Estimate of k based on the 2nd Pi value, then $k = \frac{\pi_2}{(2+1)^3}=>k=$ `r k_est`   

## Question 5
```{r question_5}

data <- -25
lambda <- 1/625
start <- matrix(625, nrow=1)
datapar <- list(data=data, lambda=1/625)

m <- 10000
varcov <- matrix(1, nrow=1)
proposal <- list(var=varcov, scale = 1050)

logNormExp <- function(sigma2, datapar) {
  X <- datapar$data
  lambda <- datapar$lambda
  loglike <- dnorm(X, sd=sqrt(abs(sigma2)), log = TRUE)
  logprior <- dexp(sigma2, rate = lambda, log = TRUE)
  return(loglike + logprior)
}

s <- rwmetrop(logNormExp, proposal, start, m, datapar)
print(s$accept)
par(mar=c(4, 4, 1, 1))
ts.plot(s$par)

par(mar=c(4, 4, 1, 1))
plot(density(s$par), main = " ")
rug(s$par)

```
    
Scale adjusted to get an acceptance rate of about 40%.   

Based on the posterior distribution it seems likely to have a mean around 625.  

## Question 6
```{r question_6}

P <- matrix(0, nrow = 40, ncol = 40)
num_rows <- num_columns <- 40
prob <- c(1/36, 2/36, 3/36, 4/36, 5/36, 6/36, 5/36, 4/36, 3/36, 2/36, 1/36)

for (i in 1:num_rows) {
  start_col <- (i + 1) %% num_columns + 1
  end_col <- start_col + length(prob) - 1
  
  if (end_col > num_columns) {
    P[i, start_col:num_columns] <- prob[1:(num_columns - start_col + 1)]
    P[i, 1:(end_col - num_columns)] <- prob[(num_columns - start_col + 2):length(prob)]
  } else {
    P[i, start_col:end_col] <- prob
  }
}
# Adjust probabilities for special cases (space 31 to space 11)
P[31, ] <- 0
P[31, 11] <- 1


# Under Original Assumptions
num_times = 1000
p1_win <- 0
p2_win <- 0 

for (i in 1:num_times) {
  state_p1 <- 1
  p1_balance <- 5000
  p1_hotel <- c(17,19,20)
  p1_rev <- c(950,950,1000)
  
  state_p2 <- 1
  p2_balance <- 5000
  p2_hotel <- c(38,40)
  p2_rev <- c(1500,2000)
  
  while(p1_balance > 0 && p2_balance > 0) {
    state_p1 <- sample(1:40, size = 1, prob = P[state_p1, ])
    state_p2 <- sample(1:40, size = 1, prob = P[state_p2, ])
    
    if (state_p2 %in% p1_hotel) {
      index <- which(p1_hotel == state_p2)
      p2_balance <- p2_balance - p1_rev[index]
      p1_balance <- p1_balance + p1_rev[index]
    }
    if (state_p1 %in% p2_hotel) {
      index <- which(p2_hotel == state_p1)
      p1_balance <- p1_balance - p2_rev[index]
      p2_balance <- p2_balance + p2_rev[index]
    }
  }
  if (p1_balance < 0){
    p2_win <- p2_win + 1
  }else{
    p1_win <- p1_win + 1
  }
}
win_num <- c(p1_win, p2_win)
print("Under original assumptions")
print(win_num/num_times)


# Under Assumption from part F
num_times = 1000
p1_win <- 0
p2_win <- 0 

for (i in 1:num_times) {
  state_p1 <- 1
  p1_balance <- 5000
  p1_hotel <- c(17,19,20,22,24,25)
  p1_rev <- c(950,950,1000,1050,1050,1100)
  
  state_p2 <- 1
  p2_balance <- 5000
  p2_hotel <- c(38,40,32,33,35)
  p2_rev <- c(1500,2000,1275,1275,1400)
  
  while(p1_balance > 0 && p2_balance > 0) {
    state_p1 <- sample(1:40, size = 1, prob = P[state_p1, ])
    state_p2 <- sample(1:40, size = 1, prob = P[state_p2, ])
    
    if (state_p2 %in% p1_hotel) {
      index <- which(p1_hotel == state_p2)
      p2_balance <- p2_balance - p1_rev[index]
      p1_balance <- p1_balance + p1_rev[index]
    }
    if (state_p1 %in% p2_hotel) {
      index <- which(p2_hotel == state_p1)
      p1_balance <- p1_balance - p2_rev[index]
      p2_balance <- p2_balance + p2_rev[index]
    }
  }
  if (p1_balance < 0){
    p2_win <- p2_win + 1
  }else{
    p1_win <- p1_win + 1
  }
}
win_num <- c(p1_win, p2_win)
print("Under assumptions from part F")
print(win_num/num_times)

```
